In [1]:
# array using numpy
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [2]:
#numpy in 0-dimensions array
import numpy as np

arr = np.array(42)

print(arr)


42


In [3]:
#creating numpy using 1-dimensions array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [4]:
#creating 2-dimesnions array using two values:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


[[1 2 3]
 [4 5 6]]
